Class {
	#name : #Gt4OpenAIMessagesGroup,
	#superclass : #Gt4OpenAIGroup,
	#category : #'Gt4OpenAI-Models'
}

{ #category : #accessing }
Gt4OpenAIMessagesGroup class >> itemClass [
	^ Gt4OpenAIChatMessage
]

{ #category : #accessing }
Gt4OpenAIMessagesGroup >> gtMessagesFor: aView [
	<gtView>
	^ aView columnedList
		title: 'Messages';
		priority: 1;
		items: [ self items ];
		column: 'Role' text: #role width: 60;
		column: 'Message' text: #content
]
