Class {
	#name : #GtLJsonPlaceholderToolExamples,
	#superclass : #GtLAbstractFunctionToolExamples,
	#category : #'Gt4LlmCore-Examples'
}

{ #category : #'as yet unclassified' }
GtLJsonPlaceholderToolExamples >> jsonPlaceholderTool [
	"Answer a valid placeholder tool."
	| tool |

	tool := GtLWebFetchTool new.
	
]

{ #category : #examples }
GtLJsonPlaceholderToolExamples >> serializeDeserialize [


]
